In [43]:
import numpy as np

In [11]:
### Scalar
a = 56
print("Scalar: ", a)

Scalar:  56


In [15]:
v = np.random.rand(5)
vector = v.reshape(-1, 1)
print("Vector:\n ", vector)

Vector:
  [[0.64816529]
 [0.10231767]
 [0.7803379 ]
 [0.54748554]
 [0.05367304]]


In [17]:
A = np.random.rand(5,6)
print("Matrix:\n ", A)

Matrix:
  [[0.65159723 0.19022273 0.2693458  0.25735974 0.97267991 0.88749726]
 [0.16418254 0.61764657 0.69560999 0.71976891 0.99411854 0.15704391]
 [0.63437272 0.53723937 0.90840825 0.820709   0.13726255 0.88687179]
 [0.57047341 0.3960441  0.38325743 0.14011446 0.86386072 0.96415711]
 [0.02986489 0.39669442 0.80144916 0.4836158  0.78837829 0.06387607]]


In [22]:
tensor = np.random.rand(5, 6, 3)
print("Tensor: \n", tensor)

Tensor: 
 [[[0.55494841 0.75780899 0.60938367]
  [0.77159654 0.49734149 0.91326996]
  [0.0097024  0.57057586 0.13225791]
  [0.11187607 0.4088924  0.90627233]
  [0.63546899 0.20624093 0.39232207]
  [0.45706944 0.2496688  0.09869877]]

 [[0.58490231 0.53159276 0.6606051 ]
  [0.70646037 0.77867452 0.37401072]
  [0.38825085 0.55779778 0.59187121]
  [0.5122441  0.96980246 0.93198584]
  [0.95541083 0.07423911 0.48274484]
  [0.69382851 0.65567724 0.40038516]]

 [[0.13730384 0.12038545 0.52270337]
  [0.0967239  0.8042677  0.29640855]
  [0.33122783 0.13589451 0.3369043 ]
  [0.2506491  0.69199945 0.6586566 ]
  [0.50510877 0.82534793 0.68941958]
  [0.15759898 0.83185849 0.60932813]]

 [[0.16162514 0.11907155 0.72388455]
  [0.45412972 0.36183031 0.79792756]
  [0.51629405 0.50058613 0.02352145]
  [0.132494   0.78974167 0.84159523]
  [0.11370005 0.75121147 0.46936495]
  [0.68790331 0.50899959 0.08716094]]

 [[0.73547783 0.05125502 0.8106639 ]
  [0.15463699 0.04958808 0.84350883]
  [0.01096218 0.9631

In [23]:
# Transpose 
print("Transpose of A: \n", A.T)

Transpose of A: 
 [[0.65159723 0.16418254 0.63437272 0.57047341 0.02986489]
 [0.19022273 0.61764657 0.53723937 0.3960441  0.39669442]
 [0.2693458  0.69560999 0.90840825 0.38325743 0.80144916]
 [0.25735974 0.71976891 0.820709   0.14011446 0.4836158 ]
 [0.97267991 0.99411854 0.13726255 0.86386072 0.78837829]
 [0.88749726 0.15704391 0.88687179 0.96415711 0.06387607]]


In [22]:
### Linear Dependence and Span:
vectors = np.random.rand(3, 3)

In [23]:
vectors

array([[0.63950099, 0.23674669, 0.75182933],
       [0.84546017, 0.16769257, 0.67191132],
       [0.91890554, 0.34327424, 0.94104654]])

In [24]:
target_vector = np.random.rand(3, 1)

In [25]:
target_vector

array([[0.59783401],
       [0.61468102],
       [0.79489764]])

In [26]:
# Determine if the vectors span the space that contains the target vector
# Hint: You can use NumPy functions to check linear dependence.
# Using Numpy: 
augmented_matrix = np.column_stack((vectors, target_vector))
rank = np.linalg.matrix_rank(augmented_matrix)
# Determine if the vectors span the space based on the rank
if rank == np.linalg.matrix_rank(vectors):
    print("The vectors span the space.")
else:
    print("The vectors do not span the space.")

The vectors span the space.


In [32]:
# Linear Dependence: 
vectors = np.array([[1, 2, 3],
                    [2, 4, 6],
                    [3, 6, 10]])
rank = np.linalg.matrix_rank(vectors)
print(rank)
if rank < min(vectors.shape):
    print("There are linearly dependent vectors in the set.")
else:
    print("There are no linearly dependent vectors in the set.")



2
(3, 3)
There are linearly dependent vectors in the set.


In [38]:
# Write code to eliminate linear dependence by removing redundant vectors
# Hint: You can use NumPy functions to find linearly independent vectors.
_,indices = np.unique(vectors, axis=0, return_index=True)


In [42]:
linear_independence_vectors = vectors[indices]
print("Linearly Independent Vectors:")
print(linear_independence_vectors)

Linearly Independent Vectors:
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6 10]]


In [46]:
# Diagonal : Used mostly in scaling and transoforming Data without altering its direction. 
# used in PCA principal componenent analysis transofrm data into a new coordinate system. 
diagonal_matrix = np.diag([2,3,4])
print("Diagonal: \n", diagonal_matrix)

Diagonal: 
 [[2 0 0]
 [0 3 0]
 [0 0 4]]


In [48]:
symmetric_matrix = np.array([[1, 2, 3],
                              [2, 4, 5],
                              [3, 5, 6]])
print("Symmetric: \n", symmetric_matrix)
print("Transpose: \n", symmetric_matrix.T)

Symmetric: 
 [[1 2 3]
 [2 4 5]
 [3 5 6]]
Transpose: 
 [[1 2 3]
 [2 4 5]
 [3 5 6]]


In [56]:
# Orthogonal: is a square matrix whose rows/columns are orthogonal. i.e: dot products of 
# rows/columns are zero and their magnitude are one. 
# Case: Orthogonal transform preserves length and angles. 
# App: Rotation, reflections and solve linear systems of equations. 
random_matrix = np.random.rand(3,3)
print("Random Matrix: \n", random_matrix)
# You can create an orthogonal matrix using special algorithms or 
#by performing QR decomposition on a matrix.
print("Orthogonal Matrix: \n", np.linalg.qr(random_matrix))

Random Matrix: 
 [[0.76629016 0.87386531 0.45166929]
 [0.9735538  0.09869962 0.58959548]
 [0.37622978 0.72341477 0.33868179]]
Orthogonal Matrix: 
 (array([[-0.59181253,  0.49390913, -0.63703351],
       [-0.75188404, -0.62311959,  0.21538889],
       [-0.29056552,  0.60644517,  0.74013237]]), array([[-1.29481909, -0.8015745 , -0.80902023],
       [ 0.        ,  0.80881978,  0.06108704],
       [ 0.        ,  0.        ,  0.0899332 ]]))


In [58]:
# Orthonormal : used in PCA and SVD 
# Create orthogonal vectors
v1 = np.array([1, 0, 0], dtype=float)
v2 = np.array([0, 1, 0], dtype=float)
v3 = np.array([0, 0, 1], dtype=float)

# # Normalize them to make them orthonormal
v1 /= np.linalg.norm(v1)
v2 /= np.linalg.norm(v2)
v3 /= np.linalg.norm(v3)

print("V1: \n", v1)
print("V2: \n", v2)
print("V3: \n", v3)

V1: 
 [1. 0. 0.]
V2: 
 [0. 1. 0.]
V3: 
 [0. 0. 1.]


In [61]:
# Use Gram-schmit : 
# Define a set of orthogonal vectors
v1 = np.array([1, 0, 0], dtype=float)
v2 = np.array([0, 1, 0], dtype=float)
v3 = np.array([0, 0, 1], dtype=float)

# Initialize a list to store orthonormal vectors
orthonormal_vectors = []

# Gram-Schmidt process to create orthonormal vectors
for v in [v1, v2, v3]:
    for u in orthonormal_vectors:
        v -= np.dot(v, u) * u
    # Normalize v to make it unit length
    norm = np.linalg.norm(v)
    print("Norm: ", norm)
    if norm > 0:
        orthonormal_vectors.append(v / norm)
    else:
        # Handle the case where v is a zero vector
        orthonormal_vectors.append(v)

# Now, orthonormal_vectors contains the orthonormal set
print("Orthonormal Vectors:")
for vector in orthonormal_vectors:
    print(vector)


Norm:  1.0
Norm:  1.0
Norm:  1.0
Orthonormal Vectors:
[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]
